//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutlookAI {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OutlookAI.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error during export:  ähnelt.
        /// </summary>
        internal static string CalendarExportError {
            get {
                return ResourceManager.GetString("CalendarExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calendar entries successfully exported! ähnelt.
        /// </summary>
        internal static string CalendarExportSuccess {
            get {
                return ResourceManager.GetString("CalendarExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error during import:  ähnelt.
        /// </summary>
        internal static string CalendarImportError {
            get {
                return ResourceManager.GetString("CalendarImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calendar entries successfully imported! ähnelt.
        /// </summary>
        internal static string CalendarImportSuccess {
            get {
                return ResourceManager.GetString("CalendarImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select some text and try again. \r\n  ähnelt.
        /// </summary>
        internal static string ComposeNotTextSelected {
            get {
                return ResourceManager.GetString("ComposeNotTextSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please formulate this email more professionally. \r\n - Do not include a subject line or signature.\r\n - Keep the salutation (you, they) as is. ähnelt.
        /// </summary>
        internal static string ComposePrompt1 {
            get {
                return ResourceManager.GetString("ComposePrompt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Revise this email so that it is more clearly structured and easier to understand, without changing the content. Do not create a subject line or signature. Keep the salutation (you, they) as is: ähnelt.
        /// </summary>
        internal static string ComposePrompt2 {
            get {
                return ResourceManager.GetString("ComposePrompt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Make this email shorter and more personal, as if you were writing to a good colleague or acquaintance:  
        ///- Do not include a subject line or signature.  
        ///- Keep the salutation (you, they) the same. ähnelt.
        /// </summary>
        internal static string ComposePrompt3 {
            get {
                return ResourceManager.GetString("ComposePrompt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Professional ähnelt.
        /// </summary>
        internal static string ComposePromptTitle1 {
            get {
                return ResourceManager.GetString("ComposePromptTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clearer ähnelt.
        /// </summary>
        internal static string ComposePromptTitle2 {
            get {
                return ResourceManager.GetString("ComposePromptTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Informal ähnelt.
        /// </summary>
        internal static string ComposePromptTitle3 {
            get {
                return ResourceManager.GetString("ComposePromptTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #TODO#_Error in the request to oLLAMA ähnelt.
        /// </summary>
        internal static string ErrorcallingOllama {
            get {
                return ResourceManager.GetString("ErrorcallingOllama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #TODO#_Error in the request to ChatGPT ähnelt.
        /// </summary>
        internal static string ErrorcallingOpenai {
            get {
                return ResourceManager.GetString("ErrorcallingOpenai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error:  ähnelt.
        /// </summary>
        internal static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error during processing:  ähnelt.
        /// </summary>
        internal static string ErrorProcessing {
            get {
                return ResourceManager.GetString("ErrorProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not published ähnelt.
        /// </summary>
        internal static string NichtVeröffentlicht {
            get {
                return ResourceManager.GetString("NichtVeröffentlicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die gpt-4o-mini ähnelt.
        /// </summary>
        internal static string OpenAiDefaultModel {
            get {
                return ResourceManager.GetString("OpenAiDefaultModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Act as an expert in professional communication, customer service, diplomacy, and problem-solving. Given the sender name and the body of one or more emails (in any language), generate the following four responses. For each response, mirror the language, tone, and length of the original email conversation, and start with an appropriate greeting.
        ///
        ///Positive Acknowledgement:
        ///Provide a response that begins with a relevant greeting, and positively acknowledges the sender’s message.
        ///
        ///Request for More Informati [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Prompt1 {
            get {
                return ResourceManager.GetString("Prompt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Write me a to-do list for the following email. Write in detail and use paragraphs to structure the argument. ähnelt.
        /// </summary>
        internal static string Prompt2 {
            get {
                return ResourceManager.GetString("Prompt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Write me a response to the following email with 3 follow-up questions. Use the same language as the email for your response. Do not include an email footer or subject line. Write in detail and in an informal style. ähnelt.
        /// </summary>
        internal static string Prompt3 {
            get {
                return ResourceManager.GetString("Prompt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Act as an expert in professional communication, customer service, diplomacy, and problem-solving. Given the sender name and the body of one or more emails (in any language), generate comprehensive and detailed responses for the following four scenarios. For every response, mirror the language, tone, and length (aiming for a substantial, fully developed reply) of the original email conversation, and start with an appropriate greeting. Assume the Mail is written to me, Falko Nuppnau 
        ///
        ///Incorporate these spec [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Prompt4 {
            get {
                return ResourceManager.GetString("Prompt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Summarize the following email, list the key statements and information, and describe the tone of the email. 
        ///
        ///Analyze the email: 
        ///Read the original email to understand the context, the issue, and the sender&apos;s tone.
        ///
        ///Incorporate content input: 
        ///Use only the provided content information and statements as the basis for the response. ähnelt.
        /// </summary>
        internal static string SummarizePrompt1 {
            get {
                return ResourceManager.GetString("SummarizePrompt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Summarize the following email. Read the original email to understand the context, the issue, and the sender&apos;s tone. ähnelt.
        /// </summary>
        internal static string SummarizePrompt2 {
            get {
                return ResourceManager.GetString("SummarizePrompt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Summary 1 ähnelt.
        /// </summary>
        internal static string SummarizeTitle1 {
            get {
                return ResourceManager.GetString("SummarizeTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Summary 2 ähnelt.
        /// </summary>
        internal static string SummarizeTitle2 {
            get {
                return ResourceManager.GetString("SummarizeTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 3 Antworten ähnelt.
        /// </summary>
        internal static string Title1 {
            get {
                return ResourceManager.GetString("Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ToDo ähnelt.
        /// </summary>
        internal static string Title2 {
            get {
                return ResourceManager.GetString("Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rückfragen ähnelt.
        /// </summary>
        internal static string Title3 {
            get {
                return ResourceManager.GetString("Title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom ähnelt.
        /// </summary>
        internal static string Title4 {
            get {
                return ResourceManager.GetString("Title4", resourceCulture);
            }
        }
    }
}
