//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutlookAI {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OutlookAI.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please formulate this email more professionally. \r\n - Do not include a subject line or signature.\r\n - Keep the salutation (you, they) as is. ähnelt.
        /// </summary>
        internal static string ComposePrompt1 {
            get {
                return ResourceManager.GetString("ComposePrompt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Revise this email so that it is more clearly structured and easier to understand, without changing the content. Do not create a subject line or signature. Keep the salutation (you, they) as is: ähnelt.
        /// </summary>
        internal static string ComposePrompt2 {
            get {
                return ResourceManager.GetString("ComposePrompt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Make this email shorter and more personal, as if you were writing to a good colleague or acquaintance:  
        ///- Do not include a subject line or signature.  
        ///- Keep the salutation (you, they) the same. ähnelt.
        /// </summary>
        internal static string ComposePrompt3 {
            get {
                return ResourceManager.GetString("ComposePrompt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Professional ähnelt.
        /// </summary>
        internal static string ComposePromptTitle1 {
            get {
                return ResourceManager.GetString("ComposePromptTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clearer ähnelt.
        /// </summary>
        internal static string ComposePromptTitle2 {
            get {
                return ResourceManager.GetString("ComposePromptTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Informal ähnelt.
        /// </summary>
        internal static string ComposePromptTitle3 {
            get {
                return ResourceManager.GetString("ComposePromptTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #TODO#_Error in the request to oLLAMA ähnelt.
        /// </summary>
        internal static string ErrorcallingOllama {
            get {
                return ResourceManager.GetString("ErrorcallingOllama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #TODO#_Error in the request to ChatGPT ähnelt.
        /// </summary>
        internal static string ErrorcallingOpenai {
            get {
                return ResourceManager.GetString("ErrorcallingOpenai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not published ähnelt.
        /// </summary>
        internal static string NichtVeröffentlicht {
            get {
                return ResourceManager.GetString("NichtVeröffentlicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die gpt-4o-mini ähnelt.
        /// </summary>
        internal static string OpenAiDefaultModel {
            get {
                return ResourceManager.GetString("OpenAiDefaultModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Write me for the following E - Mail three answer options: \ r \ n1. Use a friendly, professional tone and add possible next steps. \ R \ n2. preserved. Do not create an email or subject. Write briefly and use paragraphs to structure the argument. ähnelt.
        /// </summary>
        internal static string Prompt1 {
            get {
                return ResourceManager.GetString("Prompt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Write me a to-do list for the following email. Write in detail and use paragraphs to structure the argument. ähnelt.
        /// </summary>
        internal static string Prompt2 {
            get {
                return ResourceManager.GetString("Prompt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Write me a response to the following email with 3 follow-up questions. Use the same language as the email for your response. Do not include an email footer or subject line. Write in detail and in an informal style. ähnelt.
        /// </summary>
        internal static string Prompt3 {
            get {
                return ResourceManager.GetString("Prompt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Write a response to the following email and refer to this email. Use the language of the email for your response. Do not create any email footers or subject lines. Write in detail and use paragraphs to structure your argument. Pay special attention to the following points: ähnelt.
        /// </summary>
        internal static string Prompt4 {
            get {
                return ResourceManager.GetString("Prompt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Summarize the following email, list the key statements and information, and describe the tone of the email. 
        ///
        ///Analyze the email: 
        ///Read the original email to understand the context, the issue, and the sender&apos;s tone.
        ///
        ///Incorporate content input: 
        ///Use only the provided content information and statements as the basis for the response. ähnelt.
        /// </summary>
        internal static string SummarizePrompt1 {
            get {
                return ResourceManager.GetString("SummarizePrompt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Summarize the following email. Read the original email to understand the context, the issue, and the sender&apos;s tone. ähnelt.
        /// </summary>
        internal static string SummarizePrompt2 {
            get {
                return ResourceManager.GetString("SummarizePrompt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Summary 1 ähnelt.
        /// </summary>
        internal static string SummarizeTitle1 {
            get {
                return ResourceManager.GetString("SummarizeTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Summary 2 ähnelt.
        /// </summary>
        internal static string SummarizeTitle2 {
            get {
                return ResourceManager.GetString("SummarizeTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 3 Antworten ähnelt.
        /// </summary>
        internal static string Title1 {
            get {
                return ResourceManager.GetString("Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ToDo ähnelt.
        /// </summary>
        internal static string Title2 {
            get {
                return ResourceManager.GetString("Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rückfragen ähnelt.
        /// </summary>
        internal static string Title3 {
            get {
                return ResourceManager.GetString("Title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom ähnelt.
        /// </summary>
        internal static string Title4 {
            get {
                return ResourceManager.GetString("Title4", resourceCulture);
            }
        }
    }
}
